const THEME_TYPES = {
  radial: 'radial',
  linear: 'linear'
};

const HIGH_QLT_TRANSFORM = 'w_2048,h_2048,webpq_100';
const LOW_QLT_TRANSFORM = 'w_64,h_64,webpq_80';
const ORIENT_SCENE_TOWARDS_CAMERA = 'ORIENT_SCENE_TOWARDS_CAMERA';

export {
  THEME_TYPES,
  HIGH_QLT_TRANSFORM,
  LOW_QLT_TRANSFORM,
  ORIENT_SCENE_TOWARDS_CAMERA
};
