const loginStates = {
  OAUTH: 'OAUTH',
  EMAIL_PASSWORD: 'EMAIL_PASSWORD',
  FORGOT_PASSWORD: 'FORGOT_PASSWORD',
  RESET_PASSWORD: 'RESET_PASSWORD',
  LOGIN_FAILED: 'LOGIN_FAILED',
  LOGIN_SUCCESSFUL: 'LOGIN_SUCCESSFUL'
};

export default loginStates;
