const OVERLAY_STATE = {
  HIDE: 'HIDE',
  SHOW_LANDING_SCREEN_WITHOUT_LOGO: 'SHOW_LANDING_SCREEN_WITHOUT_LOGO',
  SHOW_LOADING_SCREEN_WITH_LOGO: 'SHOW_LOADING_SCREEN_WITH_LOGO',
  SHOW_LOGIN: 'SHOW_LOGIN',
  SHOW_SHARE: 'SHOW_SHARE'
};

export default OVERLAY_STATE;
